export const tickerItems = [
  { label: "虎虎填表可拿 3 美刀试用额度", color: "#3b82f6" },
  { label: "虎虎进 QQ 群可继续领部分免费额度", color: "#10b981" },
  { label: "dazes.cc 注册送 1 美刀，互填邀请再得 1 美刀", color: "#f59e0b" },
  { label: "Primdream 当前社区口径是价格偏高，暂不推荐", color: "#ef4444" },
];

export const guideSteps = [
  {
    index: "01",
    title: "先看倍率",
    description: "把倍率低、口径清楚的站先筛出来，避免一上来就被加价。",
  },
  {
    index: "02",
    title: "再看备注",
    description: "像日卡、周卡、模型分组、未实测这类备注，往往比数字更关键。",
  },
  {
    index: "03",
    title: "最后看入口",
    description: "能试用的先试，能看群友反馈的先看反馈，不要只盯着低价。",
  },
];

export const highlightMetrics = [
  { label: "已录入站点", value: "12", note: "按你提供的这批真实中转站先做首版观察表" },
  { label: "可直接试用入口", value: "2", note: "虎虎试用单和 dazes.cc 新人赠额都已挂到页面" },
  { label: "特殊价格口径", value: "5+", note: "含多倍率、日卡/周卡/月卡、plus/pro 分组等情况" },
  { label: "共建优先级", value: "高", note: "这批数据最需要群友继续补测和纠错" },
];

export const updateBoard = [
  "虎虎试用入口已确认可用，仍可先填表拿额度",
  "Primdream 当前社区口径更新为：价格偏高，暂不推荐",
  "xiaoya-api 已补 plus 0.15x / pro 0.25x 双口径说明",
];

export const stationSnapshots = [
  {
    name: "虎虎",
    group: "huhuai.xyz / 试用入口",
    tag: "可试用",
    price: "0.15 倍率",
    multiplier: "0.15x",
    uptime: "待群测",
    latency: "待补",
  },
  {
    name: "Aether",
    group: "to-aether.com / 社区常用",
    tag: "较稳定",
    price: "0.26 倍率",
    multiplier: "0.26x",
    uptime: "待补",
    latency: "待补",
  },
  {
    name: "妖怪杂货铺",
    group: "api.dstopology.com / 低倍率",
    tag: "便宜",
    price: "0.049 倍率",
    multiplier: "0.049x",
    uptime: "待补",
    latency: "待补",
  },
];

export const communityPosts = [
  {
    category: "集合更新",
    meta: "刚整理 · 需要大家补测",
    title: "这批中转站已经先挂上来了，接下来最缺的是稳定性和模型分组反馈",
    summary:
      "现在已经不是空样品了，而是把你给的真实站点集合先做进页面。下一步最有价值的是群友补充高峰期稳定性、实际模型可用性和价格是否持续有效。",
  },
  {
    category: "试用提醒",
    meta: "优先入口",
    title: "虎虎可以先填试用单拿 3 美刀，再进群看有没有额外免费额度",
    summary:
      "这类入口型信息适合放在首页明显位置，先让新来的人能低成本试，再决定长期用哪个站。",
  },
  {
    category: "避坑",
    meta: "社区口径",
    title: "Primdream 目前不推荐，主要是价格口径偏高",
    summary:
      "像这类带主观判断的信息不应该写成铁结论，更适合标成“当前社区口径”，后面如果价格变化再及时改。",
  },
  {
    category: "待核验",
    meta: "继续共建",
    title: "Datopology、WayX、xiaoya-api 这几类站最需要大家补第一手体验",
    summary:
      "有的站现在只有倍率或入口，没有足够的高峰稳定性和模型实际反馈，这正是大家一起补数据最能发挥作用的地方。",
  },
];

export const demoVideos = [
  {
    title: "演示视频 01",
    subtitle: "首页怎么快速找到试用入口和群友备注",
    note: "建议你后面录一个 30 秒首页导览，讲清楚怎么先试、怎么看备注。",
  },
  {
    title: "演示视频 02",
    subtitle: "榜单页怎么比较倍率、多分组价格和特殊口径",
    note: "建议录一个榜单筛选和阅读说明，尤其讲清楚同站点多倍率怎么理解。",
  },
  {
    title: "演示视频 03",
    subtitle: "怎么把新站点、纠错和群聊结论提交到仓库",
    note: "建议录一个 GitHub 协作视频，方便直接号召群友一起维护。",
  },
];

export const collaborationSteps = [
  {
    title: "先发线索",
    description: "新站点、价格变化、邀请码和试用入口先丢 Discussions 或 Issue。",
  },
  {
    title: "再补口径",
    description: "带上倍率、模型组、注册链接、截图和出现时间，尽量别只口头说。",
  },
  {
    title: "最后入表",
    description: "确认后再走 PR，把数据和文案一起正式收录到观察站里。",
  },
];

export const pendingVerifications = [
  {
    name: "WayX",
    need: "缺高峰期稳定性和模型可用反馈",
  },
  {
    name: "Datopology",
    need: "缺第一手体验，也需要确认是否与妖怪杂货铺属于同域名不同口径",
  },
  {
    name: "dasuAPI",
    need: "缺具体倍率、模型分组和价格截图",
  },
  {
    name: "xiaoya-api",
    need: "缺 plus / pro 的真实使用反馈和长期稳定性口径",
  },
];

export const contributionTasks = [
  "补一个你用过的站",
  "纠正一条过期价格",
  "提交一个试用入口",
  "补充一条避坑备注",
];

export const featuredColumns = [
  {
    title: "试用入口汇总",
    description: "把试用单、注册送额度、互填邀请这种入口统一整理成一个板块。",
  },
  {
    title: "多倍率说明",
    description: "专门解释 GPT、Claude、plus、pro、Max、日卡/周卡/月卡的不同口径。",
  },
  {
    title: "待补实测清单",
    description: "公开列出哪些站还缺群友测试，让大家知道下一步帮什么最有价值。",
  },
];

export const resourceLinks = [
  {
    title: "虎虎 API 试用单",
    href: "https://www.kdocs.cn/l/cj84YbmlJswN",
    note: "填表可获 3 美刀额度，页面里建议作为首选试用入口。",
  },
  {
    title: "API 中转站集合统计表",
    href: "https://www.kdocs.cn/l/cr2932V6f6bH",
    note: "可复制到金山文档 APP 打开，适合继续补更多站点信息。",
  },
  {
    title: "QQ群免费额度提醒",
    href: "https://www.kdocs.cn/l/cj84YbmlJswN",
    note: "虎虎这类入口进群后可能还有补充免费额度，适合继续补测。",
  },
];

export const stationComparisonRows = [
  {
    name: "Primdream",
    badge: "暂不推荐",
    group: "https://primdream.store/login",
    entry: "官网登录",
    packageType: "按倍率",
    status: "社区口径偏贵",
    models: "未细分 / 待补",
    price: "0.8 倍率",
    multiplier: "0.8x",
    uptime: "待补",
    latency: "待补",
    source: "群友整理 + 当前备注",
    verdict: "当前社区口径偏贵",
    note: "主播朋友的站，目前不推荐，主要因为价格高了。",
    advantage: "入口清楚，后续如果价格调整，有机会重新观察。",
    risk: "现阶段倍率高，不适合作为主力低价站推荐。",
  },
  {
    name: "Aether",
    badge: "常用",
    group: "https://to-aether.com/dashboard",
    entry: "Dashboard 直链",
    packageType: "按倍率",
    status: "待结构化实测",
    models: "未细分 / 社区常用",
    price: "0.26 倍率",
    multiplier: "0.26x",
    uptime: "待群测",
    latency: "待补",
    source: "群友常用口径",
    verdict: "价格还行，口碑偏稳",
    note: "群里口径是比较常用，也可以和老板商量组队压价。",
    advantage: "价格不差，当前备注里稳定性印象较好。",
    risk: "缺少结构化实测数据，仍需要群友补高峰反馈。",
  },
  {
    name: "WayX",
    badge: "待补测",
    group: "https://api.aiwxin.com/dashboard",
    entry: "Dashboard 直链",
    packageType: "按倍率",
    status: "待核验",
    models: "未细分",
    price: "0.2 倍率",
    multiplier: "0.2x",
    uptime: "待补",
    latency: "待补",
    source: "仅有倍率口径",
    verdict: "先收录，待继续反馈",
    note: "目前主要只有倍率，缺少体验层信息。",
    advantage: "倍率看起来还可以，值得继续观察。",
    risk: "没有明确稳定性和模型可用性数据。",
  },
  {
    name: "妖怪杂货铺",
    badge: "低倍率",
    group: "https://api.dstopology.com/keys",
    entry: "Keys 页面",
    packageType: "按倍率",
    status: "低价待验证",
    models: "未细分 / 低倍率",
    price: "0.049 倍率",
    multiplier: "0.049x",
    uptime: "待补",
    latency: "待补",
    source: "群友备注",
    verdict: "目前看到的倍率很低",
    note: "备注只有一句“倍率挺低的”，适合继续验证实际可用性。",
    advantage: "价格非常亮眼，容易成为首页快览重点。",
    risk: "低倍率不代表真的稳，尤其要看模型映射和高峰表现。",
  },
  {
    name: "Datopology",
    badge: "未实测",
    group: "https://api.dstopology.com/keys",
    entry: "Keys 页面",
    packageType: "待补",
    status: "完全缺样本",
    models: "未细分",
    price: "待补",
    multiplier: "-",
    uptime: "未试",
    latency: "未试",
    source: "群友待试",
    verdict: "先挂名，等第一手体验",
    note: "当前备注是“没试过，你们试试”。",
    advantage: "和妖怪杂货铺同链接，值得确认是否同站不同口径。",
    risk: "完全缺第一手数据，别写成确定推荐。",
  },
  {
    name: "Liary",
    badge: "卡制",
    group: "https://ai.liaryai.com/",
    entry: "官网入口",
    packageType: "日卡 / 周卡 / 月卡",
    status: "口径需单独解释",
    models: "日卡 / 周卡 / 月卡",
    price: "日卡/周卡/月卡",
    multiplier: "卡制",
    uptime: "待补",
    latency: "待补",
    source: "群友口径",
    verdict: "量大时可能更实惠",
    note: "不适合和纯倍率站直接横比，应该单独标口径。",
    advantage: "量大用户可能更划算。",
    risk: "必须额外解释价格口径，否则容易误导对比。",
  },
  {
    name: "五条悟api",
    badge: "群友站",
    group: "tb 搜索“群名是这个” / 五条悟api",
    entry: "淘宝搜索入口",
    packageType: "特殊口径",
    status: "入口型站点",
    models: "20 一亿 token",
    price: "20 / 1 亿 token",
    multiplier: "特殊口径",
    uptime: "待补",
    latency: "待补",
    source: "群友整理",
    verdict: "额度不少",
    note: "这是 TB 搜索入口型站点，适合单独标明获取方式。",
    advantage: "额度描述比较直观，适合低门槛试试。",
    risk: "非标准站内链接，需要在页面上说明入口方式。",
  },
  {
    name: "虎虎",
    badge: "可试用",
    group: "huhuai.xyz",
    entry: "域名入口 + 试用单",
    packageType: "按倍率",
    status: "试用友好",
    models: "未细分",
    price: "0.15 倍率",
    multiplier: "0.15x",
    uptime: "待补",
    latency: "待补",
    source: "试用单 + 群友备注",
    verdict: "先试再说",
    note: "可联系调低倍率，填表先送 3 美刀，进 QQ 群还有额外免费额度。",
    advantage: "试用入口清晰，适合新用户优先体验。",
    risk: "实际长期价格和稳定性还要继续看群友反馈。",
  },
  {
    name: "dazes.cc",
    badge: "注册送额",
    group: "https://cn.dazes.cc",
    entry: "官网登录",
    packageType: "待补",
    status: "新人友好",
    models: "未细分",
    price: "便宜 / 稳定",
    multiplier: "待补",
    uptime: "群友口径稳定",
    latency: "待补",
    source: "注册送额 + 邀请码",
    verdict: "新人友好",
    note: "注册送 1 美刀，互相填写再得 1 美刀，邀请码备注是 dGSL。",
    advantage: "门槛低，适合拿来先试。",
    risk: "“稳定”目前更多是社区口径，缺少统一实测。",
  },
  {
    name: "dasuAPI",
    badge: "待补测",
    group: "https://dasuapi.com",
    entry: "官网入口",
    packageType: "待补",
    status: "信息不完整",
    models: "未细分",
    price: "便宜 / 稳定",
    multiplier: "待补",
    uptime: "待补",
    latency: "待补",
    source: "群友正向备注",
    verdict: "先挂上，等补体验",
    note: "目前备注偏正向，但细节不够。",
    advantage: "站点入口明确，适合继续补数据。",
    risk: "缺少具体倍率与模型组信息。",
  },
  {
    name: "viptoken站",
    badge: "低倍率",
    group: "https://www.viptoken.top/dashboard",
    entry: "Dashboard 直链",
    packageType: "按倍率",
    status: "口径需核验",
    models: "0.01 倍率中转站",
    price: "0.01 倍率",
    multiplier: "0.01x",
    uptime: "待补",
    latency: "待补",
    source: "群友整理",
    verdict: "倍率极低",
    note: "倍率很低，但越低越要提醒大家去验证实际可用性和口径。",
    advantage: "很适合放在首页的低价快览里。",
    risk: "极低倍率最需要防止误读或口径不一致。",
  },
  {
    name: "xiaoya-api",
    badge: "多档位",
    group: "https://xiaoya-api.xyz",
    entry: "官网入口",
    packageType: "plus / pro 双档位",
    status: "结构清楚",
    models: "plus 0.15 / pro 0.25",
    price: "plus 0.15 倍率",
    multiplier: "pro 0.25x",
    uptime: "待补",
    latency: "待补",
    source: "群友整理",
    verdict: "需要拆开看",
    note: "同站点不同模型组倍率不同，前端应该显示成双口径而不是单值。",
    advantage: "价格分层清楚，适合做多档位展示示例。",
    risk: "如果只写一个值会误导用户。",
  },
];
